### ISSUE TITLE
TEETSigner.SignXML vracia stale false

### ISSUE THREAD

**Issue by MFsoft** [mirus77/DelphiEET#1]
Zdravím chcel som sa opýtať či ste nenarazili na problém v unite u_EETSigner.pas konkretne funkcia SignXML a v nej funkcia xmlSecDSigCtxSign vrati -1 čo a následne vyhodnotí ako false.
Nemám skúsenosti z libxmlsec, viete mi poradiť ako si vrátiť nejaké chybové hlásenie ? Alebo ako podpísať request.xml pomocou prilozeneho xmlsec1.exe

**Comment by mirus77** [comment]
Také zdravím. nezkoušel jste přeložit aplikaci jako {$APPTYPE CONSOLE} ?. XMLSec (popř. libxml) vypisuje chyby do konzole. Nevypíše to nějakou chybovou hlášku? Zatím co jsem testoval na to mi to funguje.

**Comment by MFsoft** [comment]
Skusil som to spustit cez konzolu, v konzole vypíše : 
`func=xmlSecXPathDataExecute:file=xpath.c:line=273:obj=unknown:subj=xmlXPtrEval:error=5:libxml2 library function failed:expr=xpointer(id('id-TheBody'))
func=xmlSecXPathDataListExecute:file=xpath.c:line=373:obj=unknown:subj=xmlSecXPathDataExecute:error=1:xmlsec library function failed:
func=xmlSecTransformXPathExecute:file=xpath.c:line=483:obj=xpointer:subj=xmlSecXPathDataExecute:error=1:xmlsec library function failed:
func=xmlSecTransformDefaultPushXml:file=transforms.c:line=2405:obj=xpointer:subj=xmlSecTransformExecute:error=1:xmlsec library function failed:
func=xmlSecTransformCtxXmlExecute:file=transforms.c:line=1236:obj=unknown:subj=xmlSecTransformPushXml:error=1:xmlsec library function failed:transform=xpointer
func=xmlSecTransformCtxExecute:file=transforms.c:line=1296:obj=unknown:subj=xmlSecTransformCtxXmlExecute:error=1:xmlsec library function failed:
func=xmlSecDSigReferenceCtxProcessNode:file=xmldsig.c:line=1571:obj=unknown:subj=xmlSecTransformCtxExecute:error=1:xmlsec library function failed:
func=xmlSecDSigCtxProcessSignedInfoNode:file=xmldsig.c:line=804:obj=unknown:subj=xmlSecDSigReferenceCtxProcessNode:error=1:xmlsec library function failed:node=Reference
func=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=547:obj=unknown:subj=xmlSecDSigCtxProcessSignedInfoNode:error=1:xmlsec library function failed:
func=xmlSecDSigCtxSign:file=xmldsig.c:line=303:obj=unknown:subj=xmlSecDSigCtxSignatureProcessNode:error=1:xmlsec library function failed:
func=xmlSecParseMemory:file=parser.c:line=547:obj=unknown:subj=buffer != NULL:error=100:assertion:`

prikladam xml ktore vstupuje do funkcie SignXML() tu:`<?xml version="1.0"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><SOAP-ENV:Header><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" SOAP-ENV:mustUnderstand="1"><wsse:BinarySecurityToken EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3" wsu:Id="id-TheCert"/><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="id-TheSignature"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="soap"/></ds:CanonicalizationMethod><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><ds:Reference URI="#id-TheBody"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList=""/></ds:Transform></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue></ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue></ds:SignatureValue><ds:KeyInfo Id="TheKeyInfo"><wsse:SecurityTokenReference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="id-TheSecurityTokenReference"><wsse:Reference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" URI="#id-TheCert" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3"/></wsse:SecurityTokenReference></ds:KeyInfo></ds:Signature></wsse:Security></SOAP-ENV:Header><SOAP-ENV:Body><Trzba xmlns="http://fs.mfcr.cz/eet/schema/v3"><Hlavicka uuid_zpravy="4efbf27e-3b0e-4bfe-8190-644def2993e1" dat_odesl="2016-09-22T15:54:42+02:00" prvni_zaslani="false" overeni="false"/><Data dic_popl="CZ1212121218" id_provoz="273" id_pokl="/5546/RO24" porad_cis="0/6460/ZQ42" dat_trzby="2016-09-22T15:54:42+02:00" celk_trzba="34113.00" zakl_nepodl_dph="3036.00" zakl_dan1="-820.92" dan1="-172.39" zakl_dan2="-3538.20" dan2="-530.73" zakl_dan3="9756.46" dan3="975.65" cest_sluz="5460.00" pouzit_zboz1="784.00" pouzit_zboz2="967.00" pouzit_zboz3="189.00" urceno_cerp_zuct="324.00" cerp_zuct="679.00" rezim="0"/><KontrolniKody><pkp cipher="RSA2048" digest="SHA256" encoding="base64"></pkp><bkp digest="SHA1" encoding="base16"></bkp></KontrolniKody></Trzba></SOAP-ENV:Body></SOAP-ENV:Envelope>
`

**Comment by mirus77** [comment]
První problém vidím v XML.  `<soap:Envelope ..` a `<SOAP-ENV:Header ...`. Hlavička musí být v jiném prefixu pro namespace. Docílil jsem toho upravou souboru Soap.SOAPEnv.pas v "include\soap\Soap.SOAPEnv.pas" 

Search Path: ..\include\soap;$(BDS)\source\soap; -- dojde k rekompilaci delphi SOAP a akceptování s upraveného Soap.SOAPEnv.pas

viz. 
`const
  MySSoapNameSpacePre : string = 'soap';`

Stačí přidat do search path v project options dle readme u projektu.

Příklad:
`
<?xml version="1.0"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <SOAP-ENV:Header xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    ....
  </SOAP-ENV:Header>
  <soap:Body xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="id-TheBody">
    <Trzba xmlns="http://fs.mfcr.cz/eet/schema/v3">
    ....
    </Trzba>
  </soap:Body>
</soap:Envelope>
`

**Comment by MFsoft** [comment]
Ďakujem za usmernenie, skúšal som to pod Delphi XE a tam je trocha iné definovanie classes namespace, a aj napriek pridaniu Search Pathu to išlo stále cez pôvodnú unitu delphi SOAPEnv.pas.

Každopádne teraz to zbehne a vytvorí validný  request.xml, no response.xml vrati prazdne, to ešte odkrokujem zajtra kde sa to stratí, pretože keď to pošlem cez POSTMAN server mi vráti validnú odpoveď aj z FIK

Ešte raz ďakujem za pomoc a super príklad :+1:
