### ISSUE TITLE
Odeslání

### ISSUE THREAD

**Issue by ShaneZB** [mirus77/DelphiEET#2]
Zdravím, zkouším testovací aplikaci a při odeslání SOAP vrací chybu: "EET.FErrorMessage 'Požadované záhlaví nebylo nalezeno. - URL:https://pg.eet.cz:443/eet/services/EETServiceSOAP/v3 - SOAPAction:http://fs.mfcr.cz/eet/OdeslaniTrzby'"

tohle je XML: 
<?xml version="1.0"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><SOAP-ENV:Header xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" SOAP-ENV:mustUnderstand="1"><wsse:BinarySecurityToken EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3" wsu:Id="id-TheCert">MIID6zCCAtOgAwIBAgIEAQAAAzANBgkqhkiG9w0BAQsFADBYMQswCQYDVQQGEwJDWjEaMBgGA1UEAwwRR0ZSIEVFVCB0ZXN0IENBIDExLTArBgNVBAoMJEdlbmVyw6FsbsOtIGZpbmFuxI1uw60gxZllZGl0ZWxzdHbDrTAeFw0xNjA1MTkxMjQ1MDJaFw0xODA1MTkxMjQ1MDJaMFMxCzAJBgNVBAYTAkNaMRUwEwYDVQQDDAxDWjEyMTIxMjEyMTgxFzAVBgNVBAoMDk9zb2JhIEZ5emlja8OhMRQwEgYDVQQFEwtUMDAwMDAwMDAwMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMt0eW9n+RB0PSawKSJbtAg3j7e1I5p7P9OvEj0n9raEMI496Zuw7s4VaE8JEX4iowjWhlPIOPljDiAXX6HgZzH4PDps0rFm388KZxj7Ek/ZLyyh5jRovc0Yccfgm3i2huBepk7ZtifZXOZzDEDT0CZsxRpypZJp9PK6SOdj2zPIc11F+prwsGQCDAZsRtama5/W5qn2YUWjjk+4c5Zu3TcknC7bcp1dg7RJ9yMtNiYPY7LNV3uWQhAXZVFpmOpbfYwT1F8H3/UrWDSJ5zrHshICPreMyZ0skU9SUANQ8QQKE6lSlgSs59YaeEmCyGtpttVjN+iR/L9M9FRtq3ZhZz0CAwEAAaOBwTCBvjAeBgNVHREEFzAVgRNlcG9kcG9yYUBmcy5tZmNyLmN6MB8GA1UdIwQYMBaAFHpa/A3L7DamDdppGWaMm++Cw6k0MB0GA1UdDgQWBBQbyTbuGBZdorOZZm7usMraGAJ2STBMBgNVHSAERTBDMEEGCmCGSAFlAwIBMAIwMzAxBggrBgEFBQcCAjAlGiNUZW50byBjZXJ0aWZpa2F0IEpFIFBPVVpFIFRFU1RPVkFDSTAOBgNVHQ8BAf8EBAMCBsAwDQYJKoZIhvcNAQELBQADggEBAC3L8Bm7ZlWui9xWrjM00SlvCokpc2ldGCxNvj4hANaISoLRdPVZAPeLd1X4KsRyxOIazR5oq3EKVZV1ZP3sCF4QFL+SqurkPiBbIrrbABDLyDpf/8DIfyA1x/+zNpN9ul9j9Ca1739P4L1x3wpQcYhEuvSrTiLztndlJb69LXgYZOFfqcBSRedRuMwRdtux9OWkkZjrd9wNHTCDOIfOPaPRRoq5IPHP32shsXaTLvhsT7ktvR5Fr/SQ8CkWq3U6tdcOQRN35ZWyYSyOd5/vkJqK773R/gAeBUE80gpLMdqgVj8HaD7RlHrYyYJEVUI9gbctTfUIJW/9LZ3K78JLXXg=/wsse:BinarySecurityToken<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="id-TheSignature">ds:SignedInfo<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="soap"/>/ds:CanonicalizationMethod<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><ds:Reference URI="#id-TheBody">ds:Transforms<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList=""/>/ds:Transform/ds:Transforms<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>ds:DigestValue5oIxd+ysf+647wp9fVEfLO68CDOMH55anScnpQzqmMU=/ds:DigestValue/ds:Reference/ds:SignedInfods:SignatureValuee4Kq5Abw+b/lbQ/hUNlQl5xik1Hhm8OLZ6m4kKJkbhPbC2b3BjkfcBilZ6s9IrLn/LJS9Lkj+E/h6tLeq0mks4bYIdbjYjwcnBKJvMs92dR1QFgvCkgKmiX0rv236iuDB13ZP/NfAJA0vC1jqhXPzsTs8irbFkDcTGVzof15Y6f35uv1LohQaBLLx6xj4/4JbplNydZ8phFoA6grK1D4P3za2eVu3bcpGRYdrEjCClK+uKF5bAydzLY5/lOe6TRUGIP0/IehMuCH4B07o9Klxe4xMYb+0LfLmfunBlNSJsQ9JLoazzcbgHOY1rWf8s//n7diV42/lkHmaLFW4WOYIg==/ds:SignatureValue<ds:KeyInfo Id="TheKeyInfo"><wsse:SecurityTokenReference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="id-TheSecurityTokenReference"><wsse:Reference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" URI="#id-TheCert" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3"/>/wsse:SecurityTokenReference/ds:KeyInfo/ds:Signature/wsse:Security/SOAP-ENV:Header<soap:Body xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="id-TheBody"><Trzba xmlns="http://fs.mfcr.cz/eet/schema/v3"><Hlavicka uuid_zpravy="4b4731d7-c298-4dc3-84ac-1cc7b105dae0" dat_odesl="2016-09-26T20:42:02+02:00" prvni_zaslani="false" overeni="false"/><Data dic_popl="CZ1212121218" id_provoz="273" id_pokl="/5546/RO24" porad_cis="0/6460/ZQ42" dat_trzby="2016-09-26T20:42:02+02:00" celk_trzba="34113.00" zakl_nepodl_dph="3036.00" zakl_dan1="-820.92" dan1="-172.39" zakl_dan2="-3538.20" dan2="-530.73" zakl_dan3="9756.46" dan3="975.65" cest_sluz="5460.00" pouzit_zboz1="784.00" pouzit_zboz2="967.00" pouzit_zboz3="189.00" urceno_cerp_zuct="324.00" cerp_zuct="679.00" rezim="0"/><KontrolniKody><pkp cipher="RSA2048" digest="SHA256" encoding="base64">a/uDO1iVhy1H393C32HJQiG+L/QWtyJc1KwwRL+SbTN0Y4NEf7ReoxWAm/CBU/ixfxWyh5cPVaYgjUcgX/05ckMjTo7JQUzN5lGoN6FGlOaWH3F8aRNq4rZvQkdJ6ngMusC9VEAM/NqXkdxybKtznHdkd3Y5sQ0SgmOvuaUT05JeFPamsjEezK1+dsbquZfgWjKojkfHZskw8iA6Pt5V1aO/XySDlaHHuH0xxwllmS0/AQiQVVrcI7eDFfEPC4ta8kCQqoEXiCvsdc3XBf6v/p+bruVyIPQFTDdyldnmooyZ3FqFBXThI+dU4XnSYNPD9RbA3FqZhb4qrTLcpi+AfQ==</pkp><bkp digest="SHA1" encoding="base16">B0DDEC4E-50405476-A5F606B8-7D6E4A6B-4AAE446C</bkp></KontrolniKody></Trzba>/soap:Body/soap:Envelope

Nemám nejmenší tušení, v čem je problém a jak postupovat. Moc prosím o nakopnutí.

**Comment by mirus77** [comment]
Také zdravím :
Zkuste se jsem vložit XML jako kód tlačítko `<>`
Výsledek by měl vypadat takto viz níže.
`<?xml version="1.0"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <SOAP-ENV:Header xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" SOAP-ENV:mustUnderstand="1">
      <wsse:BinarySecurityToken EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3" wsu:Id="id-TheCert">MIID6zCCAtOgAwIBAgIEAQAAAzANBgkqhkiG9w0BAQsFADBYMQswCQYDVQQGEwJDWjEaMBgGA1UEAwwRR0ZSIEVFVCB0ZXN0IENBIDExLTArBgNVBAoMJEdlbmVyw6FsbsOtIGZpbmFuxI1uw60gxZllZGl0ZWxzdHbDrTAeFw0xNjA1MTkxMjQ1MDJaFw0xODA1MTkxMjQ1MDJaMFMxCzAJBgNVBAYTAkNaMRUwEwYDVQQDDAxDWjEyMTIxMjEyMTgxFzAVBgNVBAoMDk9zb2JhIEZ5emlja8OhMRQwEgYDVQQFEwtUMDAwMDAwMDAwMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMt0eW9n+RB0PSawKSJbtAg3j7e1I5p7P9OvEj0n9raEMI496Zuw7s4VaE8JEX4iowjWhlPIOPljDiAXX6HgZzH4PDps0rFm388KZxj7Ek/ZLyyh5jRovc0Yccfgm3i2huBepk7ZtifZXOZzDEDT0CZsxRpypZJp9PK6SOdj2zPIc11F+prwsGQCDAZsRtama5/W5qn2YUWjjk+4c5Zu3TcknC7bcp1dg7RJ9yMtNiYPY7LNV3uWQhAXZVFpmOpbfYwT1F8H3/UrWDSJ5zrHshICPreMyZ0skU9SUANQ8QQKE6lSlgSs59YaeEmCyGtpttVjN+iR/L9M9FRtq3ZhZz0CAwEAAaOBwTCBvjAeBgNVHREEFzAVgRNlcG9kcG9yYUBmcy5tZmNyLmN6MB8GA1UdIwQYMBaAFHpa/A3L7DamDdppGWaMm++Cw6k0MB0GA1UdDgQWBBQbyTbuGBZdorOZZm7usMraGAJ2STBMBgNVHSAERTBDMEEGCmCGSAFlAwIBMAIwMzAxBggrBgEFBQcCAjAlGiNUZW50byBjZXJ0aWZpa2F0IEpFIFBPVVpFIFRFU1RPVkFDSTAOBgNVHQ8BAf8EBAMCBsAwDQYJKoZIhvcNAQELBQADggEBAC3L8Bm7ZlWui9xWrjM00SlvCokpc2ldGCxNvj4hANaISoLRdPVZAPeLd1X4KsRyxOIazR5oq3EKVZV1ZP3sCF4QFL+SqurkPiBbIrrbABDLyDpf/8DIfyA1x/+zNpN9ul9j9Ca1739P4L1x3wpQcYhEuvSrTiLztndlJb69LXgYZOFfqcBSRedRuMwRdtux9OWkkZjrd9wNHTCDOIfOPaPRRoq5IPHP32shsXaTLvhsT7ktvR5Fr/SQ8CkWq3U6tdcOQRN35ZWyYSyOd5/vkJqK773R/gAeBUE80gpLMdqgVj8HaD7RlHrYyYJEVUI9gbctTfUIJW/9LZ3K78JLXXg=</wsse:BinarySecurityToken>
      <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="id-TheSignature">
        <ds:SignedInfo>
          <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
            <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="soap"/>
          </ds:CanonicalizationMethod>
          <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
          <ds:Reference URI="#id-TheBody">
            <ds:Transforms>
              <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList=""/>
              </ds:Transform>
            </ds:Transforms>
            <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
            <ds:DigestValue>gtX7jFLgFj0hGWS3viyJ/FoguaZVw67E7uM7Itw36ik=</ds:DigestValue>
          </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>OV+qaVm6DhsutQx1eljAafV2fFHmdaqv3emdY2Jeg6vqkLaMvJwZL50kXerFYHgrtov9lhB4dVrg6+enWpNTH3ujSMZ4pN8dtUILT1nL0yCCE/ZGupWTs8CeC6bAYKS6OvotCsXMQk2Qfuqsalk0VwgntwryoAkB0JHF0J4Ktpj2kP+M4p4IkEOFH4KNiMwZnPEOQ+/oHeNbbG2uKmmQ1qJwbb3ijljOhoEMd40UOiBm4jEk53xBDfTegO0AEwDUvq3cwTAVLNTRqlrYML9kNUUbl8NSaKIq5aQHZTp8Gf5bKAe6Sk1myTaQcG8nFaIWAlj6IfWASqAe1cxe3/9AoQ==</ds:SignatureValue>
        <ds:KeyInfo Id="TheKeyInfo">
          <wsse:SecurityTokenReference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="id-TheSecurityTokenReference">
            <wsse:Reference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" URI="#id-TheCert" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3"/>
          </wsse:SecurityTokenReference>
        </ds:KeyInfo>
      </ds:Signature>
    </wsse:Security>
  </SOAP-ENV:Header>
  <soap:Body xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="id-TheBody">
    <Trzba xmlns="http://fs.mfcr.cz/eet/schema/v3">
      <Hlavicka uuid_zpravy="bad6a0ea-93dd-4f13-8448-b7abbba7821c" dat_odesl="2016-09-22T23:13:36+02:00" prvni_zaslani="false" overeni="false"/>
      <Data dic_popl="CZ1212121218" id_provoz="273" id_pokl="/5546/RO24" porad_cis="0/6460/ZQ42" dat_trzby="2016-09-22T23:13:36+02:00" celk_trzba="34113.00" zakl_nepodl_dph="3036.00" zakl_dan1="-820.92" dan1="-172.39" zakl_dan2="-3538.20" dan2="-530.73" zakl_dan3="9756.46" dan3="975.65" cest_sluz="5460.00" pouzit_zboz1="784.00" pouzit_zboz2="967.00" pouzit_zboz3="189.00" urceno_cerp_zuct="324.00" cerp_zuct="679.00" rezim="0"/>
      <KontrolniKody>
        <pkp cipher="RSA2048" digest="SHA256" encoding="base64">cve+epmM54aKPH4/IJoba60DJHihJWIaLsjtBud52vshJjTsPmqOgI7vXyKFitZ5d7gXj7z8vIH9Ah2YtiBHd1rZ1Us73oyKjim3DSzsG+eNUslyMWiVofNBwCi7EplCH63xBJQcqzKIDwMQJUiHT3fB7miZbar/DxiaLFWHEdsbPMpdbpq7mgushfhNZ9ookWLJRK+1shp7+0tD8nWAv2sWyhngC1OIpcAauQ/rJsEH1iTODKy1sfTKw2WZAarLewTxyhEMj3JF04zgdA0ZtEAh91xvn2axRgm7v9Aa741tzSpAHBUSovbU12HzQSxDoQC0dNEadly99xl8IG+4Gg==</pkp>
        <bkp digest="SHA1" encoding="base16">748EBECE-ADF424D3-FB7D2DC2-92046214-89FF925C</bkp>
      </KontrolniKody>
    </Trzba>
  </soap:Body>
</soap:Envelope>`

**Comment by ShaneZB** [comment]
Omlouvám se, ale nepochopil jsem, co mám zkusit.

**Comment by mirus77** [comment]
Myslel jsem tím, že máte sem vložit nepovedený request XML lépe a to pomocí tlačítka "Insert Code" v záhlaví komentáře. XML z Vašeho prvního dotazu bylo nečitelné (špatně interpretován komentářem), protože jste ho nevložil jako programový kód. Vyzkoušejte si nejprve Preview na komentářem a porovnejte výsledek XML zobrazení se zdrojem.
Včera jsem aktualizoval programový kód. Stáhněte si aktuální verzi. Zjednodušil jsem vytváření SOAP zprávy.

**Comment by ShaneZB** [comment]
`<?xml version="1.0"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><SOAP-ENV:Header xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" SOAP-ENV:mustUnderstand="1"><wsse:BinarySecurityToken EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3" wsu:Id="id-TheCert">MIID6zCCAtOgAwIBAgIEAQAAAzANBgkqhkiG9w0BAQsFADBYMQswCQYDVQQGEwJDWjEaMBgGA1UEAwwRR0ZSIEVFVCB0ZXN0IENBIDExLTArBgNVBAoMJEdlbmVyw6FsbsOtIGZpbmFuxI1uw60gxZllZGl0ZWxzdHbDrTAeFw0xNjA1MTkxMjQ1MDJaFw0xODA1MTkxMjQ1MDJaMFMxCzAJBgNVBAYTAkNaMRUwEwYDVQQDDAxDWjEyMTIxMjEyMTgxFzAVBgNVBAoMDk9zb2JhIEZ5emlja8OhMRQwEgYDVQQFEwtUMDAwMDAwMDAwMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMt0eW9n+RB0PSawKSJbtAg3j7e1I5p7P9OvEj0n9raEMI496Zuw7s4VaE8JEX4iowjWhlPIOPljDiAXX6HgZzH4PDps0rFm388KZxj7Ek/ZLyyh5jRovc0Yccfgm3i2huBepk7ZtifZXOZzDEDT0CZsxRpypZJp9PK6SOdj2zPIc11F+prwsGQCDAZsRtama5/W5qn2YUWjjk+4c5Zu3TcknC7bcp1dg7RJ9yMtNiYPY7LNV3uWQhAXZVFpmOpbfYwT1F8H3/UrWDSJ5zrHshICPreMyZ0skU9SUANQ8QQKE6lSlgSs59YaeEmCyGtpttVjN+iR/L9M9FRtq3ZhZz0CAwEAAaOBwTCBvjAeBgNVHREEFzAVgRNlcG9kcG9yYUBmcy5tZmNyLmN6MB8GA1UdIwQYMBaAFHpa/A3L7DamDdppGWaMm++Cw6k0MB0GA1UdDgQWBBQbyTbuGBZdorOZZm7usMraGAJ2STBMBgNVHSAERTBDMEEGCmCGSAFlAwIBMAIwMzAxBggrBgEFBQcCAjAlGiNUZW50byBjZXJ0aWZpa2F0IEpFIFBPVVpFIFRFU1RPVkFDSTAOBgNVHQ8BAf8EBAMCBsAwDQYJKoZIhvcNAQELBQADggEBAC3L8Bm7ZlWui9xWrjM00SlvCokpc2ldGCxNvj4hANaISoLRdPVZAPeLd1X4KsRyxOIazR5oq3EKVZV1ZP3sCF4QFL+SqurkPiBbIrrbABDLyDpf/8DIfyA1x/+zNpN9ul9j9Ca1739P4L1x3wpQcYhEuvSrTiLztndlJb69LXgYZOFfqcBSRedRuMwRdtux9OWkkZjrd9wNHTCDOIfOPaPRRoq5IPHP32shsXaTLvhsT7ktvR5Fr/SQ8CkWq3U6tdcOQRN35ZWyYSyOd5/vkJqK773R/gAeBUE80gpLMdqgVj8HaD7RlHrYyYJEVUI9gbctTfUIJW/9LZ3K78JLXXg=</wsse:BinarySecurityToken><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="id-TheSignature"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="soap"/></ds:CanonicalizationMethod><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><ds:Reference URI="#id-TheBody"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList=""/></ds:Transform></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>m4XqD6/Ga0tWSjbKc6CpaQQsVQV5o/CpBpcQX9PGHZE=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>grRrWtMoyxkgYRr03Mbg4q/FX2yJ2lUfumwI5Jg8U+36wdv8b1210Gr7CK0xmC/QjhD1Ll9RbykNrd/G3WoOJDloNEKUwfqGkwLoFcuZzwGTdrcJZC0bUMJ9Bh8GK5Zxz9JhWyASKZV40F34g9zvmOmgo0CEqZSWfFsBeXuRxY3iCEgwmeOKTT6FbvQ17JT+wyq9pqMWnu77zNvhN4TB8wNFKV3JIQCfkIWND0POaYpjHwM2tiI9ztJbUis2EutgBpjFzjx4UoB1dOjLorM56SBbQTcA/NgKG+fD3F7Oyey9XWxRJSJSMFGYPwHfLcmZYJm2wjAN1QuG4oq4f00T2A==</ds:SignatureValue><ds:KeyInfo Id="TheKeyInfo"><wsse:SecurityTokenReference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="id-TheSecurityTokenReference"><wsse:Reference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" URI="#id-TheCert" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3"/></wsse:SecurityTokenReference></ds:KeyInfo></ds:Signature></wsse:Security></SOAP-ENV:Header><soap:Body xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="id-TheBody"><Trzba xmlns="http://fs.mfcr.cz/eet/schema/v3"><Hlavicka uuid_zpravy="b8cb95ea-aa1c-4a94-b0f9-aced567b1c7b" dat_odesl="2016-09-27T10:16:41+02:00" prvni_zaslani="false" overeni="false"/><Data dic_popl="CZ1212121218" id_provoz="273" id_pokl="/5546/RO24" porad_cis="0/6460/ZQ42" dat_trzby="2016-09-27T10:16:41+02:00" celk_trzba="34113.00" zakl_nepodl_dph="3036.00" zakl_dan1="-820.92" dan1="-172.39" zakl_dan2="-3538.20" dan2="-530.73" zakl_dan3="9756.46" dan3="975.65" cest_sluz="5460.00" pouzit_zboz1="784.00" pouzit_zboz2="967.00" pouzit_zboz3="189.00" urceno_cerp_zuct="324.00" cerp_zuct="679.00" rezim="0"/><KontrolniKody><pkp cipher="RSA2048" digest="SHA256" encoding="base64">E+tbej2kxmCQymEu5AJE166qfh7WpYTvrwjmTnmhWUl+970shHwIk8ZAmtzWhvt+sUXel2gQNCdiO7G3osZiL4RnHKAs/X/IncyDZKVGFDHKkIE6Ai/EaKBM6AjjOab9Z1vSMIu43HJZFxuOrjsSeZ3SFWxIsg4o03a5iV1KMetu1osp5prVP/YAFBlm7bHqR7ew5PUiPjQl1T8zhitMpZLCxSfV/tNCZaXg6nd+exOZs9cuF9A3zBTDApb4JkG25op3sm3z/n9s51cMFm6i8DyBNgHYrJ9x6IdLqgnXUSYU8XDjnyC13RnY6JyNnVFLmWFcJFA2fU/ysujq/1zmHg==</pkp><bkp digest="SHA1" encoding="base16">75393807-681FF38E-C2225377-42663D94-9A25122D</bkp></KontrolniKody></Trzba></soap:Body></soap:Envelope>
`
tak druhý pokus ...

**Comment by mirus77** [comment]
Request XML se zdá být v pořádku. Stáhnětě si aktuální verzi z GitHubu. Vyzkoušejte, pokud nepůjde, tak zkontrolujte nastavení v project options ohledně "Defines" USE_INDY a Search Path ${BDS}\Source\soap.
Pokud demo spouštíte na WinXP, tak určitě musí být toto nastaveno.
Nastavení viz Readme nebo zdroj DPR souboru.

**Comment by ShaneZB** [comment]
Mám D10 seatle. Po stažení nové verze mi to nešlo zkompilovat. Udělal jsem tuto úpravu v u_EETTrzba:
`TEETTrzba = class(TComponent)
  private
.
.
    {$IFDEF USE_INDY}
    FOnVerifyPeer: TVerifyPeerEvent;
    {$ENDIF}
.
.
`
(přidal jsem prekompilační test USE_INDY)

Chyba je stále stejná. Jen požadavek začíná "<SOAP-ENV:Envelope" místo "<soap:Envelope"

**Comment by mirus77** [comment]
ad) Chyba je stále stejná. Jen požadavek začíná "<SOAP-ENV:Envelope" místo "<soap:Envelope"

Toto je v pořádku: To je poslední úprava. Je to zjednodušení. Z počátku vývoje jsem to odlišoval, ale nakonec to funguje i se společným namespace prefixem dohromady.

Spouštíte TestEET na Windows XP?

**Comment by ShaneZB** [comment]
Server 2012

**Comment by ShaneZB** [comment]
Teď jsem to prubnul na Win10 a prošlo to ...

**Comment by ShaneZB** [comment]
Na server 2003 to taky nejede

**Comment by mirus77** [comment]
Mě to to na Win Server 2012 projde. Pod uživatelem, který je ve skupině administrators. Obě verze jak INDY verze, tak WinInet verze. Na složku TestEET\Bin jsem nastavil plná oprávnění, kvůlu zápisu na disk pro ladící účely TestEET. Pod běžným uživatelem jsem ještě nezkoušel.

**Comment by mirus77** [comment]
Ještě jednou upozorňuji na Windows XP chodí pouze INDY verze. Je to dáno OS Windows XP a nepodporou potřebného TLS šifrování.

**Comment by mirus77** [comment]
Teď jsem to zkoušel. Na Win Server 2008 a také neprošla WinInet verze. S tou samou chybou co vám. Určitě je to díky omezení IE přístupu na internet. Použijte INDY verzi a půjde to. Info viz. Readme a DPR souboru. 
`
Delphi Compiler Options -> Conditional Defines : USE_INDY
`
`
Delphi Compiler Options -> Search Path: $(BDS)\source\soap;..\include\databinding;..\include\eet;..\include\synapse;..\include\szutils;..\include\xmlsec
`

**Comment by ShaneZB** [comment]
Jo. pod Indy o jede.

**Comment by ShaneZB** [comment]
Jo. pod Indy o jede.
