### ISSUE TITLE
Platnost certifikátu

### ISSUE THREAD

**Issue by ShaneZB** [mirus77/DelphiEET#3]
Zdar, budu mít účtenky uložené v databázi (hlavně kvůli opakovanému odesílání) a budu si tam ukládat i použitý certifikát. Rád bych si s ním uložil i okamžik konce platnosti, ale nevím, jak ho zjistit (v TEETSigner to není). Nebo je to stejně k ničemu a bude třeba před kařdým odesláním kontrolovat platnost certifikátu? Mimochodem, jak ji zjistím? ;-)

**Comment by mirus77** [comment]
Přidal jsem zjištění datumů platnosti v TEETSigner. Datum je přístupný(načten) z privátního klíče po zavolání  `EET.Initialize;` viz demo. Bez nutnosti volat odeslání tržby.

**Comment by ShaneZB** [comment]
Skvělá práce! :+1:  Ještě bych se nějak potřeboval jednoduše dostat k PKP (abych ho mohl tisknout, když není FIK). Je mi jasné, že bych mohl parsovat request XML, ale snad existuje lepší cesta. Zkoušel jsem "Trzba.KontrolniKody.pkp.Text", ale ten je, i po odeslání, prázdný :-)

**Comment by mirus77** [comment]
Přemístil jsem generování PKP a BKP.
Doplnil jsem před odeslání PKP a BKP do "Trzba.KontrolniKody.pkp.Text" "Trzba.KontrolniKody.bkp.Text".
PKP je dostupné vždy nezávisle na úspěšnosti odeslání tržby.
