### ISSUE TITLE
Úložiště certifikátů

### ISSUE THREAD

**Issue by ShaneZB** [mirus77/DelphiEET#4]
Nemám o tom žádné vědomosti, ale nedali by se brát ty certifikáty z úložiště certifikátů? Přišlo by mi to pro uživatele snažší a bezpečnější. Místo souborů by se předávali názvy (z certifiátů v úložišti) a heslo. Akorát bych ještě musel být schopný zobrazit uživateli seznam, aby si mohl vybrat privátní certifikát a pod.

**Comment by mirus77** [comment]
Kdyby se chtělo brát (resp. použít) certifikáty ze systémového uložiště, tak je potřeba drobná úprava v EETSigneru, ale hlavně by xmlsec musel být zkompilován i s knihovnou xmlsec-mscrypto. To u těchto binárních knihoven nebylo dostupné. Výběr certifikátu by se musel udělat ručně pomocí cryptoAPI a poté xmlsec jenom předat identifikátor toho klíče a xmlsec-mscrypto to tímto certifikátem podepíše. Použití xmlsec-mscrypto funguje třeba i pro ověření certifikátů ze systémového uložiště certifikátů.
Xmlsec-mscrypto.dll je vlastně jako podknihovna (plugin) pro xmlsec. Knihovna openssl neumí pracovat s certifikáty v systémové uložišti. 
Ve výsledku je hlavně potřeba získat xmlsec s podporou mscrypto (né moc stará verze), třeba i vlastním zkompilováním ze zdrojů. Pak se už s tím dá něco dělat.

**Comment by kremlacek** [comment]
Zdravím. Je to super! 
V readme je upraveno Search Path přidáním ..\include\vcruntime, ale v souboru projektu tato úprava chybí.
Kdo nepřečte readme bude chvíli tápat.

**Comment by kremlacek** [comment]
Ještě k demu: Je-li kompilováno bez USE_INDY přebývá VerifyPeer v implementaci u_main.

**Comment by mirus77** [comment]
Opraveno.
