### ISSUE TITLE
libeetsigner and problem with peetSignerMakeBKP and peetSignerMakePKP and 0 in hash

### ISSUE THREAD

**Issue by delphicz** [mirus77/DelphiEET#5]
Hi, 

[fail.txt](https://github.com/mirus77/DelphiEET/files/612049/fail.txt)

when used USE_LIBEET
peetSignerMakeBKP return 
75E6FBE5-05852E38-F27D235C-844068E9-9F54
but original dlls return
75E6FBE5-05852E38-F27D235C-844068E9-9F5400AB

I think, that there is a problem with 0 check in string in dll.
When hash contains 0, returning buffer is truncated.
Demo fail.xml is in attachent.
Test case
`
procedure TTestEETForm.Button1Click(Sender: TObject);
var
  ms: TMemoryStream;

  eTrzba : Trzba;
  EET : TEETTrzba;
begin
  ms := TMemoryStream.Create;
    EET := TEETTrzba.Create(nil);
    EET.URL := 'https://pg.eet.cz:443/eet/services/EETServiceSOAP/v3';

    eTrzba := Trzba.Create;
    EET.RootCertFile := 'q:\crmxev5\delphieet\demo\bin\eet\Geotrust_PCA_G3_Root.pem';
    EET.PFXStream.LoadFromFile('q:\crmxev5\delphieet\demo\bin\eet\EET_CA1_Playground-CZ00000019.p12');
    EET.AddTrustedCertFromFileName('q:\crmxev5\delphieet\demo\bin\eet\trusted_CA_pg.der');
    EET.AddTrustedCertFromFileName('q:\crmxev5\delphieet\demo\bin\eet\trusted_CA_prod.der');
    EET.AddTrustedCertFromFileName('q:\crmxev5\delphieet\demo\bin\eet\trusted_CA_prod_ROOT.der');
    EET.PFXPassword := 'eet';
    EET.ConnectTimeout := 2000;
    EET.Initialize;
    ms.LoadFromFile('q:\crmxev5\delphieet\demo\fail.xml');
    ms.Position := 0;
    EET.LoadFromXML(eTrzba, ms);

    EET.SignTrzba(eTrzba);
    ShowMessage(eTrzba.KontrolniKody.bkp.Text);
end;
`

**Comment by mirus77** [comment]
Fixed libeetsigner.dll in version 0.9.1. Do pull this projekt or download new version libeetsigner.dll from this project.
