### ISSUE TITLE
Nejde přeložit pro win xp

### ISSUE THREAD

**Issue by karelxkk** [mirus77/DelphiEET#6]
HTTPWebNode nemá IOHandler.  Na win10 to jde s WinInet. 2hý den mám RAD studio a budu mít co dělat abych to EET do března zprovoznil.

> Checking project dependencies...
Building TestEET.dproj (Debug, Win32)
brcc32 command line for "TestEET.vrc"
  c:\program files (x86)\embarcadero\studio\18.0\bin\cgrc.exe -c65001 TestEET.vrc -foTestEET.res 
dcc32 command line for "TestEET.dpr"
  c:\program files (x86)\embarcadero\studio\18.0\bin\dcc32.exe -$O- -$W+ --no-config -B -Q -TX.exe -AGenerics.Collections=System.Generics.Collections;
  Generics.Defaults=System.Generics.Defaults;WinTypes=Winapi.Windows;WinProcs=Winapi.Windows;DbiTypes=BDE;DbiProcs=BDE;DbiErrs=BDE -DDEBUG;USE_LIBEET;
  USE_INDY -E../bin -I"c:\program files (x86)\embarcadero\studio\18.0\source\soap";..\include\databinding;..\include\eet;..\include\synapse;
  ..\include\szutils;..\include\xmlsec;..\include\vcruntime;"c:\program files (x86)\embarcadero\studio\18.0\lib\Win32\release";
  C:\Users\xkk\Documents\Embarcadero\Studio\18.0\Imports;"c:\program files (x86)\embarcadero\studio\18.0\Imports";
  C:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp;"c:\program files (x86)\embarcadero\studio\18.0\include";
  C:\Users\xkk\Documents\Embarcadero\Studio\18.0\CatalogRepository\SynEdit-1.1\source -LEC:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl 
  -LNC:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp -NU./dcu -NSWinapi;System.Win;Data.Win;Datasnap.Win;Web.Win;Soap.Win;Xml.Win;Bde;Vcl;
  Vcl.Imaging;Vcl.Touch;Vcl.Samples;Vcl.Shell;System;Xml;Data;Datasnap;Web;Soap; -O"c:\program files (x86)\embarcadero\studio\18.0\source\soap";
  ..\include\databinding;..\include\eet;..\include\synapse;..\include\szutils;..\include\xmlsec;..\include\vcruntime;"c:\program files 
  (x86)\embarcadero\studio\18.0\lib\Win32\release";C:\Users\xkk\Documents\Embarcadero\Studio\18.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\18.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp;"c:\program files (x86)\embarcadero\studio\18.0\include";
  C:\Users\xkk\Documents\Embarcadero\Studio\18.0\CatalogRepository\SynEdit-1.1\source -R"c:\program files (x86)\embarcadero\studio\18.0\source\soap";
  ..\include\databinding;..\include\eet;..\include\synapse;..\include\szutils;..\include\xmlsec;..\include\vcruntime;"c:\program files 
  (x86)\embarcadero\studio\18.0\lib\Win32\release";C:\Users\xkk\Documents\Embarcadero\Studio\18.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\18.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp;"c:\program files (x86)\embarcadero\studio\18.0\include";
  C:\Users\xkk\Documents\Embarcadero\Studio\18.0\CatalogRepository\SynEdit-1.1\source -U"c:\program files (x86)\embarcadero\studio\18.0\source\soap";
  ..\include\databinding;..\include\eet;..\include\synapse;..\include\szutils;..\include\xmlsec;..\include\vcruntime;"c:\program files 
  (x86)\embarcadero\studio\18.0\lib\Win32\release";C:\Users\xkk\Documents\Embarcadero\Studio\18.0\Imports;"c:\program files 
  (x86)\embarcadero\studio\18.0\Imports";C:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp;"c:\program files (x86)\embarcadero\studio\18.0\include";
  C:\Users\xkk\Documents\Embarcadero\Studio\18.0\CatalogRepository\SynEdit-1.1\source -K00400000 
  -NBC:\Users\Public\Documents\Embarcadero\Studio\18.0\Dcp -NHC:\Users\Public\Documents\Embarcadero\Studio\18.0\hpp\Win32 -NO./dcu   TestEET.dpr   
[dcc32 Hint] u_EETSigner.pas(40): H2219 Private symbol 'ExtractSubjectItem' declared but never used
[dcc32 Error] u_EETTrzba.pas(457): E2003 Undeclared identifier: 'IOHandler'
[dcc32 Fatal Error] u_main.pas(49): F2063 Could not compile used unit 'u_EETTrzba.pas'
Failed
Elapsed time: 00:00:01.2

**Comment by mirus77** [comment]
Zkuste zjistit existenci obsahu složky c:\program files (x86)\embarcadero\studio\18.0\source\soap, Podle těchto symptomů se zřejmě nedaří znovu přeložit SOAP ze zdrojových kódů, aby to šlo přes INDY.
Zdrojové kódy budou dostupné zřejmě až od Delphi edice Profesional (včetně).
USE_INDY je zřejmě použito. To je správně.
Pokud jsou SOAP zdroje dostupné, tak by mělo jít i IDE se prokliknout přes IOHandler do zdrojů. (Ctrl+Click na IOHandler v editoru).
Ve výstupní složce ./dcu by měla být Soap.SOAPHTTPTrans.dcu po kompilaci.

**Comment by karelxkk** [comment]
Mám nainstalované Starter Berlin RAD Studio 10.1 update 2. Mám ho 3 dny.
Nemám c:\program files (x86)\embarcadero\studio\18.0\source\soap a v source mám jen Indy10,
které jsem překládal ze zdrojových souborů. Soap.SOAPHTTPTrans.dcu a Soap.WebNode.dcu
mám pouze v c:\program files (x86)\embarcadero\studio\18.0\lib\win32\release, nainstalované
při instalaci RAD.

**Comment by mirus77** [comment]
Tak bude potřeba najít jinou cestu. Dala by se využít knihovna libeetsigner.dll(nebo si vytvořit SOAP XML a podepsat komponentou TEETSigner) a k tomu TIdHTTP z Indy pro odeslání.
Knihovna libeetsigner z XML elementu  `<Trzba>...</Trzba>` dokáže vygenerovat celý SOAP Request XML, podepsat a poté je třeba výsledek postnout pomocí např. TIdHttp. A z výsledné odpovědi vyparsovat xml odpověď.

Anebo jak již bylo někde psáno použít pod WinXP nějaký SSLTunel pro spojení se serverem EET a z TestEET odeslat pouze HTTP Soap bez SSL a pomocí WinInet.

A nebo použít openeetlite.dll, která je v NETu a ta snad funguje i pod WinXP.

Ještě existuje přímo od IndyProject knihovna SOAPIndy, ale nevím v jakém je stavu. Nikdy jsem nezkoušel.
http://www.indyproject.org/SOAP/

**Comment by mirus77** [comment]
Zkuste si nyní stáhnout aktuální verzi z DelphiEET. Přidal jsem tam funkci TEETTrzba.OdeslaniTrzbyDirectIndy

**Comment by mirus77** [comment]
Není třeba používat USE_INDY. 
USE_LIBEET jenom řeší jiný způsob zpracování a generování SOAP zprávy. S USE_LIBEET se používá jenom knihovna libeetsigner.dll k tomu je potřeba mít VC++Runtime 2013 nejsou potřeba knihovny libxml, xmlsec atd. Indy používá OpenSSL DLL knihovny. A mělo by ot fungovat pod WinXP (netestoval jsem).

**Comment by karelxkk** [comment]
Děkuji. Staženo, otestováno na Windows 2003 SP2 a funguje to. Potřebuje to dll knihovny:
`Volume in drive Z has no label.
 Volume Serial Number is B0C2-F1C8

 Directory of Z:\EET\bin

13.01.2017  17:58    <DIR>          .
13.01.2017  17:58    <DIR>          ..
13.01.2017  05:24         2˙056˙192 libeay32.dll
13.01.2017  05:24         1˙963˙008 libeetsigner.dll
13.01.2017  05:24           119˙988 libgcc_s_dw2-1.dll
13.01.2017  05:24            65˙181 libwinpthread-1.dll
13.01.2017  05:24           460˙800 ssleay32.dll
13.01.2017  16:14         3˙959˙808 TestEET.exe
               6 File(s)      8˙624˙977 bytes
               2 Dir(s)  33˙158˙275˙072 bytes free`
