### ISSUE TITLE
Broken after Windows update

### ISSUE THREAD

**Issue by zebrabit** [mirus77/DelphiEET#7]
Does not work after  Windows 10 updates KB4074588 and KB4087256. (also on Windows Server 2012)
Message:  eetSignerShutdown could not be loaded from the dynamic library libeetsigner.dll
Delphi XE7 Win32

**Comment by mirus77** [comment]
I have KB4074588 also on Windows 10, and I do not have a problem with libeetsigner.dll (current version 1.0.2). This DLL need only MSVCR120.DLL (this found in Visual C++ Runtime 2013 package). Now tested.

**Comment by zebrabit** [comment]
Yes,it is working with the correct MSVCR120.DLL in the same folder.
Thanks for helping.
