### ISSUE TITLE
Delphi 10.3 RIO - HTTPWebNode: THTTPReqResp property SendTimeout removed

### ISSUE THREAD

**Issue by jindrichvolek** [mirus77/DelphiEET#9]
Please, is it possible to update to RIO? Thx

**Comment by mirus77** [comment]
New version pushed.
Distributed on the http client and producing the SOAP request from the XML Schema. It is possible to write your own HTTP client to send the request. Tested in Delphi 7, 2007, X2 Tokyo, X3 Rio. For more information, see demo project and README.
